<?xml version="1.0" encoding="UTF-8"?>
<script xmlns="http://dtf.org/v1" name="try_catch">
    <info>
        <author>
            <name>Rodney Gomes</name>
            <email>rlgomes@yahoo-inc.com</email>
        </author>
        <description>DTF try/catch unit test.</description>
    </info>
    
    <local>
        <createstorage id="INPUT" path="${dtf.xml.path}/input"/>
        <loadproperties uri="storage://INPUT/ut.properties"/>
        
		<lockcomponent id="DTFA1" timeout="60s"/>
        <echo>Try/Catch and Fail Unit Test</echo>
    </local>
    
    <try>
        <sequence>
            <local>
                <fail message="Failure should be caught by catch."/>
                <fail message="This part should never be executed."/>
            </local>
        </sequence>
        <catch exception="${dtf.FailException}">
            <sequence>
                <local>
                    <echo>The previous statement has failed correctly.</echo>
                </local>
            </sequence>
        </catch>
    </try>
    
    <try>
        <sequence>
            <try>
                <sequence>
                    <local>
                        <fail message="Failure should be caught by catch."/>
                        <fail message="This part should never be executed."/>
                    </local>
                </sequence>
                <catch exception="sun.com.dtf.exception.WrongException">
                    <sequence>
                        <local>
                            <echo>This should never be seen.</echo>
                        </local>
                    </sequence>
                </catch>
            </try>
        </sequence>
        <catch exception="${dtf.FailException}" property="fail.message">
            <sequence>
                <local>
                    <echo>Caught the exception on outter try/catch.</echo>
                    <echo>Message: ${fail.message}</echo>
                </local>
            </sequence>
        </catch>
    </try>
   
    <try>
        <sequence>
		    <component id="DTFA1">
		    	<fail message="Failing on component"/>
		    </component>
        </sequence>
        <catch exception="${dtf.FailException}" property="fail.message">
            <sequence>
                <local>
                    <echo>Caught exception from remote component.</echo>
                    <echo>Message: ${fail.message}</echo>
                </local>
            </sequence>
        </catch>
    </try>
    
</script>
